title: Paddle The Bay 25' Planning and Logistics
description: Planning, Safety And Logistics For The 40km Paddle Across Donegal Bay
url: https://iarxm.github.io/bpad
repository: iarxm/bpad
base-url: bpad

theme: jekyll-theme-minimal

markdown: kramdown

